version: '3.8'

services:
  screener-core:
    build:
      context: .
      dockerfile: Dockerfile.screener-core
    ports:
      - "8080:8080"
    depends_on:
      - redis

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - screener-core

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"