FROM golang:1.18 AS builder

WORKDIR /app

COPY go.mod go.sum ./
COPY ./cmd/api-gateway/ ./cmd/api-gateway/
COPY ./internal/ ./internal/
COPY ./pkg/ ./pkg/
COPY ./configs/ ./configs/
COPY ./Temp/ ./Temp/

RUN go mod download
RUN go build -o api-gateway ./cmd/api-gateway/main.go

FROM gcr.io/distroless/base

COPY --from=builder /app/api-gateway /api-gateway
COPY --from=builder /app/configs /configs
COPY --from=builder /app/Temp /Temp

CMD ["/api-gateway"]