api:
  host: "localhost"
  port: 8080
  websocket:
    path: "/ws"
    ping_interval: 30
    read_buffer_size: 1024
  cors:
    allowed_origins:
      - "*"
    allowed_methods:
      - "GET"
      - "POST"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"