exchange: "bybit" # legacy single exchange, kept for backward compatibility
exchanges: ["gate", "bybit", "bitget", "okx"]
symbol: "BTC-USDT"
api_key: ""
secret: ""

redis: 
  host: "localhost"
  port: 6379

logging: 
  level: "info"
  file: "logs/screener.log"

# Performance tuning
data_channel_buffer: 8192         # 8k–32k в зависимости от нагрузки
redis_workers: 8                  # 8–16 воркеров
redis_pipeline_size: 300          # батч пайплайна 200–500
subscribe_batch_size: 100         # подписываться пачками по N символов
subscribe_batch_pause_ms: 150     # пауза между пачками, мс
metrics_period_sec: 5             # период агрегированных логов

# Bitget-specific tuning (WS limits: 10 msgs/s, 240 subs/hour, <=1000 streams)
bitget_subscribe_batch_size: 30   # сколько инстр. в одном сообщении подписки
bitget_subscribe_pause_ms: 700    # пауза между батчами, мс
bitget_ping_interval_sec: 25      # интервал ping