exchange: "bybit" # legacy single exchange, kept for backward compatibility
exchanges: ["gate", "bybit"]
symbol: "BTC-USDT"
api_key: ""
secret: ""

redis: 
  host: "localhost"
  port: 6379

logging: 
  level: "info"
  file: "logs/screener.log"