FROM golang:1.18 AS builder

WORKDIR /app

COPY ./cmd/screener-core ./cmd/screener-core
COPY ./internal ./internal
COPY ./pkg ./pkg
COPY ./configs ./configs
COPY ./scripts ./scripts

RUN go build -o screener-core ./cmd/screener-core/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/screener-core .

CMD ["./screener-core"]