FROM golang:1.18 AS builder

WORKDIR /app

COPY ./cmd/api-gateway/ ./cmd/api-gateway/
COPY ./internal/ ./internal/
COPY ./pkg/ ./pkg/
COPY ./configs/ ./configs/
COPY go.mod go.sum ./

RUN go mod download
RUN go build -o api-gateway ./cmd/api-gateway/main.go

FROM gcr.io/distroless/base

COPY --from=builder /app/api-gateway /api-gateway

CMD ["/api-gateway"]